### ISSUE TITLE
`.add()` serializes all input data to a giant binary string before uploading

### ISSUE THREAD

**Issue by alexander255** [ipfs/py-ipfs-api#104]
This is obviously a no-go.

**Comment by whereswaldon** [comment]
Are you referring to the generators in `multipart.py`? If so, how do you propose to change it? Is your concern uploading large files (and therefore taking up inordinate amounts of RAM)?

**Comment by alexander255** [comment]
> Are you referring to the generators in `multipart.py`?

Ignore them they are just distraction and not actually used when uploading a directory 😁.

Instead [this code is called](https://github.com/ipfs/py-ipfs-api/blob/master/ipfsapi/multipart.py#L526-L528), which (internally) serializes everything to one giant byte string which is [later retrieved and returned](https://github.com/ipfs/py-ipfs-api/blob/master/ipfsapi/multipart.py#L409).

Steps to reproduce:

 1. Try uploading a large directory: `client.add(os.path.expanduser("~/Videos"))`
 2. Observe the memory usage of the client exploding

**Comment by pjz** [comment]
Pertinent: http://docs.python-requests.org/en/master/user/advanced/#streaming-uploads
