### ISSUE TITLE
Drop "made by Protocol Labs" badge?

### ISSUE THREAD

**Issue by alexander255** [ipfs/py-ipfs-api#107]
Looking at our [contribution page](https://github.com/ipfs/py-ipfs-api/graphs/contributors), the largest contribution a protocol labs employee has made to this project was @RichardLitt by updating our README with the mentioned badge. Even IBM et al has made more contributions to this project than Protocol Labs 😉.

Unless Protocol Labs hires me or @whereswaldon, I think it would only be honest to drop that badge in our next release. 🙂 

Any objections?

**Comment by RichardLitt** [comment]
None from my end. I included that in all of the IPFS repos, but it may not fit here. :)

**Comment by machawk1** [comment]
@alexander255 This can probably be closed per 4be777d940892ffde44f44d6e662764a67e9804d.

**Comment by alexander255** [comment]
Indeed, thanks for pointing it out. 🙂
