### ISSUE TITLE
Documentation link no longer works

### ISSUE THREAD

**Issue by machawk1** [ipfs/py-ipfs-api#109]
The README suggests looking to https://ipfs.io/ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfsapi/ for documentation but upon accessing the link, the following message appears:

> ipfs resolve -r /ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfsapi/: Could not resolve name.

...with no other documentation.

**Comment by alexander255** [comment]
That was quick! (Only three hours after the IPNS link expired, apparently.)

I had planned on fixing this yesterday, but got delayed. Sorry for the inconvinence!
