### ISSUE TITLE
Outdated keyword under usage in readme?

### ISSUE THREAD

**Issue by Restaldt** [ipfs/py-ipfs-api#113]
Not really much of an issue but i didnt know where else to put this:

under your usage section in the readme:

Add a directory and match against a filename pattern:

>>> api.add('photos', match='*.jpg')
[{'Hash': 'QmcqBstfu5AWpXUqbucwimmWdJbu89qqYmE3WXVktvaXhX',
  'Name': 'photos/photo1.jpg'},
 {'Hash': 'QmSbmgg7kYwkSNzGLvWELnw1KthvTAMszN5TNg3XQ799Fu',
  'Name': 'photos/photo2.jpg'},
 {'Hash': 'Qma6K85PJ8dN3qWjxgsDNaMjWjTNy8ygUWXH2kfoq9bVxH',
  'Name': 'photos/photo3.jpg'}]

match doesnt seem to be the right keyword anymore changing it to pattern fixes the error that this now throws (at least for me) 

 api.add(r'photos',pattern='*.png')

**Comment by whereswaldon** [comment]
Huh. Yeah, that's odd. I'll have to check on that soon. Thanks for pointing this out!
