### ISSUE TITLE
Documentation link doesn't work

### ISSUE THREAD

**Issue by Cole128** [ipfs/py-ipfs-api#121]
The directory the IPNS link leads to is empty. I would love to have actual documentation so I can use the library.

**Comment by alexander255** [comment]
Fixed. The IPNS link is a great demo of how reliable that system currently is…

**Comment by VictorBjelkholm** [comment]
> how reliable that system currently is

It's as reliable as it was designed to be currently :) Make sure you update the record once every ~24 hours (or more often) as the records expire.

**Comment by alexander255** [comment]
The problem I have encountered way more often is that the daemon will “forget” it's own published records and then stop publishing anything.

**Comment by VictorBjelkholm** [comment]
@alexander255 that sounds like a serious bug if that so. Could you please open up a bug report in ipfs/go-ipfs with as much information as possible about it? That should definitely not happen.

**Comment by alexander255** [comment]
@VictorBjelkholm: I have exactly 0 information other than „it happens sometimes when the daemon doesn't run for a couple of hours“. Exactly the kind of bug report that tends to be ignored and finally closed being non-reproducible. That's why I didn't bother.

**Comment by alexander255** [comment]
Anyways I just realized that the `ipfs/go-ipfs` doesn't have the latest tag set to `v0.4.14` – which is why I still was at `v0.4.13`. Supposidly the update will fix some IPNS related things so we will see, I guess.
