### ISSUE TITLE
Redirect Get to \dev\null

### ISSUE THREAD

**Issue by davinci26** [ipfs/py-ipfs-api#132]
Hey guys, 

Thanks for the API!!!!!

Is it possible to redirect the output of ipfs.get to \dev\null\?

**Comment by davinci26** [comment]
Thanks a lot!

Ooops the slash direction was a typo.

I am trying to simulate a content distribution network, and I want to measure the download speed under various conditions so I want to avoid storing unnecessary files that's why I don't do pin_add. I garbage collect the daemon right after I finish with the downloading.

Who are you 🙀?

**Comment by whereswaldon** [comment]
@davinci26 Did one of these solutions end up working for your use-case?

**Comment by davinci26** [comment]
@whereswaldon I didnt try the directory solution as I was not interested in it. However, the single file solution worked fine for me.

**Comment by stmoreau** [comment]
@davinci26 I would like to know as well who @alexander255 is!

Can I trust this guy? Can I trust you?

Your profile info says:
`Mentalist, show me your repo's and ill tell you who you are`

**Comment by whereswaldon** [comment]
@davinci26 Since that worked for you, I'm going to close this for now.
