### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by swedneck** [ipfs/py-ipfs-api#135]
Seeing as this has been reported and fixed before i'm a bit hesitant to report it, but better safe than sorry!

**Comment by whereswaldon** [comment]
The docs are hosted via IPFS on one of the dev's machines. Unfortunately, they aren't pinned in many places, so they tend to disappear when that machine goes offline for any reason. If you'd like to help, you can pin the docs to your own IPFS nodes!

**Comment by alexander255** [comment]
The docs are not down and are hosted on my server, however they do sometimes need quite some time until they are loaded – especially when `ipfs.io` is overloaded again.

**Comment by radfish** [comment]
Just FYI: in the py-ipfs-httpclient branch the link is broken due to the renaming:
https://ipfs.io/ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfshttpclient/

```
ipfs resolve -r /ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfshttpclient/: no link named "ipfshttpclient" under QmPkXGx17pqqktjdRQnVrPz3sr21U5NjhTV1CTMvzaX1dw
```

When ipfshttclient becomes the main branch, please remember to pin the renamed docs directory.

**Comment by alexander255** [comment]
@radfish: Yes, I haven't pushed any documentation with the new code yet, but will do once we release the first version.

**Comment by alexander255** [comment]
The new `ipfs-http-client` library now has a different documentation link on its own IPNS ID (not on my machine's node one as previously). Previously it had been different because back when we published the first documentation snapshots, none-node-ID IPNS names weren't even a thing yet.
