### ISSUE TITLE
Missing word in documentation

### ISSUE THREAD

**Issue by codeluggage** [ipfs/py-ipfs-api#136]
There might be more of these but this was the only one I saw. The word `kwargs` (presumably) is missing from the documentation here: https://ipfs.io/ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfsapi/api_ref.html#the-api-client

I'm assuming it refers to `kwargs` because I see the same sentence here: https://github.com/ipfs/py-ipfs-api/blob/master/docs/api_ref.md#the-api-client

Looks like it's simply missing, and not a display or formatting issue, given the html: 

<img width="623" alt="screen shot 2018-08-03 at 8 25 10 am" src="https://user-images.githubusercontent.com/1154150/43642872-2aa37904-96f7-11e8-81c4-94ed4794aa2f.png">

**Comment by whereswaldon** [comment]
Hmm... You're totally right. I wonder what's making that disappear. Thanks for bringing this to our attention!

**Comment by whereswaldon** [comment]
Had a hard time deciding how to categorize this. Ultimately, it's a bug in our documentation, so I decided that it doesn't deserve the normal "bug" label.

**Comment by AliabbasMerchant** [comment]
Hi. I think I got the solution to this problem.  
I would like to contribute.  
I should branch from master, right??

**Comment by whereswaldon** [comment]
Resolved via #141
