### ISSUE TITLE
New IPFS Client Maintainers Group

### ISSUE THREAD

**Issue by mikeal** [ipfs/py-ipfs-api#142]
Hiya :)

In the IPFS org we’ve [created a new group](https://github.com/ipfs/community/issues/352#issuecomment-440380041) for maintainers of client libraries. This will make it easier for us to loop you into issues that may cause problems or necessitate changes in your client library.

If you could let us know the github usernames of all the active maintainers we can add them to the group and note them in the [clients table](https://github.com/ipfs/ipfs#http-client-libraries).

Also, we have a great [IPFS weekly newsletter](https://tinyletter.com/ipfsnewsletter). A few days before each edition goes out a new pull request is created [in the repo](https://github.com/ipfs/newsletter). If you have any announcements related to your client library feed free to log a new issue in the repo or just comment on an upcoming newsletter pull request.

**Comment by alexander255** [comment]
@mikeal: Thanks for the link to the newsletter. Subscribed!
As for the active maintainers of this library, that'd be: @alexander255 & @whereswaldon 
Both of us are doing stuff on a minimal as-needed basis, so we're not really developers at the moment but we try to keep things working. :slightly_smiling_face:

**Comment by mikeal** [comment]
Added to the team and to the table update PR :) https://github.com/ipfs/ipfs/pull/377/files#diff-04c6e90faac2675aa89e2176d2eec7d8
