### ISSUE TITLE
Editorconfig - Python configuration?

### ISSUE THREAD

**Issue by AuHau** [ipfs/py-ipfs-api#164]
I noticed that @alexander255 added .editorconfig, which is very appreciated. Only I am a bit confused with the settings as they do not really match typical Python's configuration.

Here are my typical settings:
```
[*.py]
indent_style = space
indent_size = 4
trim_trailing_whitespace = true
insert_final_newline = true
max_line_length = 120 # or 79 to follow strictly PEP8
```

Should I create PR for it, or is there some reason why not to have this setting?

**Comment by alexander255** [comment]
This is intentional :wink:
I just happen to like it that way and I'm doing most of the work around here, so whatever.

Thanks for reaching out through!
