### ISSUE TITLE
release 0.4.3 not tagged

### ISSUE THREAD

**Issue by radfish** [ipfs/py-ipfs-api#176]
Could you please add a tag for 0.4.3 (the release tags are used by distro packages to construct version strings, here's the one I made for Arch https://aur.archlinux.org/packages/python-ipfshttpclient-git/), also while at it, maybe also post it as a release on GH too. Thanks!

**Comment by alexander255** [comment]
Upps, I had tagged it on my machine but the tag wasn't pushed – should be available now. For official releases please refer to [PyPI](https://pypi.org/project/ipfsapi/#files). The sdist there is automatically generated by `flit` but should still work.
Thanks for the heads-up and distributing this library!
