### ISSUE TITLE
Unclear documentation of command options

### ISSUE THREAD

**Issue by pjz** [ipfs/py-ipfs-api#33]
In the README, you show both

    api.pin_ls(opts={'type':'all'})

and also

    api.add('fake_dir', recursive=True)

...which is correct usage?

In particular, I'm trying to do the equivalent of `ipfs pin add -r`, but it's unclear to me whether it should be:

    api.pin_add(addr, recursive=True)

or

    api.pin_add(addr, opts={"recursive":"True"})

or maybe something else?

**Comment by amstocker** [comment]
The `recursive` keyword argument is only for convenience for the `add` function at the moment, so for pinning it should be `api.pin_add(addr, opts={"recursive":"True"})` as you said.

**Comment by alexander255** [comment]
0cab366c73a3c71f858befcc42f2c36fd64c2df9 has added python keyword arguments for every known IPFS option. Using `opts` is still possible and supported, but shouldn't be necessary, except in special circumstances.
