### ISSUE TITLE
_object_new undefined

### ISSUE THREAD

**Issue by jgraef** [ipfs/py-ipfs-api#34]
I just tried calling `object_new`, which in turns tries to call `_object_new`. But `_object_new` is not defined. Patch attached.
[object_new.patch.txt](https://github.com/ipfs/python-ipfs-api/files/82771/object_new.patch.txt)

**Comment by whereswaldon** [comment]
This should be resolved by #46

**Comment by whereswaldon** [comment]
Since I believe that #46 fixed this, I'm closing it for now. Please post again if you experience more problems with it.
