### ISSUE TITLE
Drop support for Python 2.6?

### ISSUE THREAD

**Issue by whereswaldon** [ipfs/py-ipfs-api#44]
My team and I have been working on documenting and testing this library, but much of our testing is made harder by the Python 2.6 support that this library currently has. We've added support for Python 3.5 to our version, and we'd like to remove support for 2.6. Does anyone have a problem with that?

**Comment by alexander255** [comment]
Well apparently nobody else is responding, so I go…
As far as I'm concerned dropping Python 2.6 support is a nobrainer and has been overdue for some time. Definitely feel free to go ahead! :smiley:

**Comment by whereswaldon** [comment]
Thanks for responding! Will do. Our changes should start appearing in the form of PRs in the next week or so.
