### ISSUE TITLE
Files add accepts unused filename filter

### ISSUE THREAD

**Issue by whereswaldon** [ipfs/py-ipfs-api#49]
The recursive add functionality does not currently use the filter that it accepts to check the names of files. This should be implemented.

**Comment by whereswaldon** [comment]
Compared to some other problems within the repo, this doesn't seem like a huge priority. I looked at what it might take to implement this, but I'm not going to try to do it just yet.

Implementation notes: This needs to be addressed on several levels:
- `ipfsApi.multipart.DirectoryStream._prepare` has access to the `fnpattern` because it's a property of the `DirectoryStream` object. However, it doesn't do anything with this.
- `ipfsApi.commands.FileCommand.request` does not accept an `fnpattern` explicitly, though `ipfsApi.commands.FileCommand.directory` does accept a `match` pattern that will be passed to the `DirectoryStream` (see above). Since `FileCommand.request` dispatches either `FileCommand.files` or `FileCommand.directory` based upon whether the add path is a directory, it needs to pass the pattern when it invokes `FileCommand.directory`, but not `FileCommand.files` (otherwise the request library gets angry about an unexpected keyword argument). 
- The `ipfsApi.client.add` function needs to accept a pattern (optionally) that is propagated down to the `DirectoryStream` if a directory is being added. Otherwise, it need not propagate it.

I'd welcome thoughts about a better approach to implementing this, as well as questions if my notes above don't make sense.

**Comment by heaven00** [comment]
@whereswaldon close this ?

**Comment by alexander255** [comment]
Yes, this has been fixed thanks to you :smiley:
