### ISSUE TITLE
No pydoc documentation

### ISSUE THREAD

**Issue by larsks** [ipfs/py-ipfs-api#5]
The methods on an API client object have no documentation:

    >>> import ipfsApi
    >>> api = ipfsApi.Client()
    >>> help(api.ls)

This yields documentation on the `partial`  class, which isn't terribly helpful.  It is also impossible to ask for documentation on these methods using `pydoc`:

    $ pydoc ipfsApi.Client.ls
    no Python documentation found for 'ipfsApi.Client.ls'

This all seems very developer-unfriendly.

**Comment by BrendanBenshoof** [comment]
The way @amstocker  is building the commands is elegant, but make it hard to insert the pydoc documentation.

If we keep this style, we need to essentially add the documentation in the definitions at client.py and ensure it is carried through to the partial function (we can then over-write the pydoc for partial with our desired pydoc)

I'm not sure I like this solution.

**Comment by BrendanBenshoof** [comment]
I'm starting a re-write of client.py so we can make both of these things work.

**Comment by amstocker** [comment]
I like your idea for the rewrite of client.py and I think it makes a lot of sense.  However at this point we should get rid of the prepare method altogether and just do e.g. return self._add.request(client, path, **kwargs)

**Comment by whereswaldon** [comment]
#46 added some pep257-style documentation, but I'll try to work pydoc in soon as well.

**Comment by whereswaldon** [comment]
This issue essentially subsumes the #26 's "Write doc strings for all api methods"
