### ISSUE TITLE
Streamline functional/tests exec by doing a pre-check for a running ipfs daemon

### ISSUE THREAD

**Issue by joshisa** [ipfs/py-ipfs-api#53]
If no ipfs daemon is present/running, the tox test runs/hangs for a lengthy period of time when entering the functional/tests portion.  It might be a more streamlined experience to perform a pre-check on the ipfs daemon state and fail fast rather than running/hanging.

**Comment by alexander255** [comment]
You are right about feedback being a bit low atm when `ipfs deamon` isn't running. I've implemented a tiny decorator that should fix this (locally), but I'm not sure if I should fail or skip those tests. Ideally those tests should be skipped but a big warnings messages should be shown instead; something that apparently isn't possible. :disappointed: 

What do you think? Skip them or fail them? Do you know of any way to show a message for a skipped test?

**Comment by whereswaldon** [comment]
I think my feeling is that there should be a test for having the daemon running in the first place. If there's no daemon, that fails. Then the rest of the functional tests should be skipped. That way you get the feedback that the daemon isn't running, but don't have to wait for all of the tests to fail. Thoughts?

**Comment by alexander255** [comment]
I had similar thoughts on this, so I'l just do as you suggested @whereswaldon.
