### ISSUE TITLE
Discussion: Inconsistent module names

### ISSUE THREAD

**Issue by whereswaldon** [ipfs/py-ipfs-api#56]
To install py-ipfs-api with pip, you run `pip install ipfs-api`, but to use it in a python file you write `import ipfsApi`.

I think this is because python doesn't allow hyphens in module names, which is understandable. However, this package effectively goes by three names.

1. The git repo is `py-ipfs-api`,
2. The pip package is `ipfs-api`,
3. And the module is `ipfsApi`

Can/Should anything be done to make this more consistent? I think it's probably confusing to new users (I know it confused me at first), but I don't know how hard to change it would be, or how bad of an idea that might be. Thoughts?

**Comment by alexander255** [comment]
Me too.
I think the module name should simply be `ipfsapi`, similar to how other python modules in the stdlib were (re)named (like `ConfigParser` → `configparser`). The PIP package could also be renamed accordingly.

**Comment by jbenet** [comment]
- my only request is to keep with the many-language conventions: `<lang>-ipfs-api` for the repo. `ipfs-api` (or `ipfsapi`) for package names.

**Comment by whereswaldon** [comment]
Okay, consensus is (and I agree with this):

- Repo name: py-ipfs-api
- PIP package: ipfsapi
- module: ipfsapi

Are we agreed?

**Comment by alexander255** [comment]
This has been fixed with #67
