### ISSUE TITLE
Use Flit for packaging?

### ISSUE THREAD

**Issue by whereswaldon** [ipfs/py-ipfs-api#71]
@alexander255 Just discovered a package/util for making uploading to PyPI easier. Might simplify our process. It's called [Flit](https://pypi.python.org/pypi/flit), and it is configured through an ini file instead of a setup.py file. I believe that it is cross-platform too, which is nice. Thoughts?

**Comment by alexander255** [comment]
I've looked at back when you opened the issue, but didn't write a response yet. Sorry.

I really like what `flit` is trying to achieve, but I'm really worried about compatibility with existing implementations of `pip` (see https://github.com/takluyver/flit/issues/74). Also `flite` apparently hard-codes the useage of `README.rst` for the package description (which we converted to MarkDown when [switching to the standardized-README](https://github.com/ipfs/py-ipfs-api/pull/43)), but I think this would probably be something that can be worked around easily enough.
I'm also not sure how/if this would interact with testing?

My current verdict: Maybe, but it needs some thorough investigation first. Maybe we should wishlist this?

**Comment by alexander255** [comment]
So I looked at `flit` again the last couple of days and I'm very happy with what I see: 😁 

 * [X] `flit` can now create sdist files (by generating a tiny setuptools-style package)
 * [X] Flit has a [hidden feature](https://github.com/takluyver/flit/issues/127#issuecomment-320707779) for reading the decription from MarkDown files and converting it on-the-fly to ReST by call `pandoc` through `pypandoc`, see: https://github.com/takluyver/flit/issues/127
    * This is very similar to [our current hack](https://github.com/ipfs/py-ipfs-api/blob/master/setup.py#L18), but less ugly (for us at least)
    * The author has also “[doesn't] see any reason to get rid of the hidden pandoc feature, and if I ever do, I'll do so with a deprecation cycle unless there's a really good reason that's not practical.” – So this feature shouldn't just disappear overnight
    * The latest PyPA specs actually [specify a new `Description-Content-Type` field](https://packaging.python.org/specifications/#description-content-type), that can be used by packages to signal that their description isn't in reStructuredText, but in MarkDown or plain text (but Python Warehose and Legacy-PyPI don't support it yet). So there is a clear migration path into the future here.
 * [X] Testing works after applying a small tweak to `tox`' configuration

I've uploaded a demo of the flit-converted package here: https://test.pypi.org/project/ipfsapi/

Unless any grave issues are discovered we should totally do this! :+1:

**Comment by alexander255** [comment]
We now use `flit`! \o/
