### ISSUE TITLE
Separate out encoding.py as multicodec ?

### ISSUE THREAD

**Issue by heaven00** [ipfs/py-ipfs-api#73]
The `encoding.py` code seems a lot like multicodec implementation, should we separate it out ? so that it can be used in py-ifps too ?

**Comment by whereswaldon** [comment]
I looked around a little, but didn't find the multicodec specs. What is it responsible for? `encoding.py` basically just handles, JSON and a couple other formats. Is that the purpose of multicodec?

**Comment by heaven00** [comment]
yeah, that's the purpose of it, more details https://github.com/multiformats/multicodec

so its one of the requirements listed here too https://github.com/ipfs/py-ipfs/issues/23

**Comment by alexander255** [comment]
I like the idea, but reviewing the current `multicodec` spec it seems the current `encoding.py` only handles the “how do I decode data with the given type” part; it doesn't actually provide a multicodec parser yet.
My suggestion would therefore be to start an independent project that provides a full `multicodec` implementation (optionally based on `encoding.py`). Once it reaches the level of maturity required to be usable on it's own (particularly by the `py-ipfs` project), we can then integrate it into this project and (possibly) make it an official `ipfs` project (at least I would do some lobbying towards that goal).

**Comment by fredthomsen** [comment]
I have started a python multicodec implementation https://github.com/fredthomsen/py-multicodec.  I believe only json works correctly right now.  I'll look and seeing if we can integrate this.

**Comment by heaven00** [comment]
lets complete the module first and then integrate ?
I would love to help out too on this :)

**Comment by fredthomsen** [comment]
Another problem is that we need to make py-multicodec support streaming, currently it only takes fixed length rather than streams.

**Comment by alexander255** [comment]
I've looked at https://github.com/multiformats/py-multicodec (now existing multicodec implementation in Python) and it doesn't look like `encoding.py` at all. Leading me to believe that this was some kind of misunderstanding here. If anything, `encoding.py` (or rather the library written by @fredthomsen) seems to more closely resemble what https://github.com/ipld/py-ipld-dag would like to achieve if it contained any code. With recent changes `encoding.py` is now hardly more than a glorified JSON parser and even before that there wasn't much to “separate out” in the first place.
This will therefor be closed, open a new issue if you think that you can provide a replacement for `encoding.py` but for now we'll stick to the required JSON and byte stream handling.
