### ISSUE TITLE
Regression: ipfs add no longer works for folders

### ISSUE THREAD

**Issue by Netherdrake** [ipfs/py-ipfs-api#75]
```
In [28]: !ipfs add  -r tmp/
added QmQDze3FMH2GxVfomdghYeLGAkQ4QJrvcMGKykW7zBwJUH tmp/Devcon2_-_Orbit_-_Distributed__real-time_Web3_application_with_IPFS_and_Ethereum.pdf
added QmSTbjW14eBr8ZgJzxjDtEFF9CBhVccvjkbcGeiMthm6xC tmp/Maker_Devcon2.pdf
added QmXKtze4Z97osJGjvRZPLb8cfhf2sh2nShy9zqsxTTnrFf tmp/Zcash-slides.pdf
added QmTkEnbpLjuotXxqK8Wyn4tozMJXaAwqBtQguKQ7yyo4kf tmp/test/site4.png
added QmeMBXfX3xqQnoxPa4We5rLoMxqcbUmqDSnsDKAXFtW8yY tmp/test
added QmQsYbAp34mGm4RHxZxjpRruWzoWEAcVyq5m43tegA6psq tmp

In [29]: c.add('tmp/', recursive=True)
Out[29]: 
[{'Hash': 'QmT5DQ74JNwwhH7y5LmAjEND9Yu1iukaxBhdjQnwxMCHj8', 'Name': 'tmp/'},
 {'Hash': 'QmPtdDjMCtf3BgMytQqwfMfvru6bmxNDAHyvMjaivYKCuY', 'Name': 'tmp'}]

In [30]: c.add('tmp', recursive=True)
Out[30]: {'Hash': 'QmRkjAFXWVfY9DQvfeQJ2UfGdvEygJQVoS3YkfobEDDVo8', 'Name': 'tmp'}

In [31]: 
```

Furthermore, QmRkjAFXWVfY9DQvfeQJ2UfGdvEygJQVoS3YkfobEDDVo8, QmPtdDjMCtf3BgMytQqwfMfvru6bmxNDAHyvMjaivYKCuY and QmT5DQ74JNwwhH7y5LmAjEND9Yu1iukaxBhdjQnwxMCHj8 appears to be garbage.

**Comment by alexander255** [comment]
Thanks for reporting this! Are you using the legacy `ipfsApi` (for IPFS 0.3.x) or the updated `ipfsapi` (for IFPS 0.4+) module?
This looks very similar to #41.

**Comment by Netherdrake** [comment]
Ahh, the issue has been spotted. I am traveling, so I'm working on another computer. I tried using `ipfsApi` on ipfs v.0.4.2, which doesn't seem to work.

Thanks for the tip, I didn't know about `ipfsapi` :)

Everything works well now.
