### ISSUE TITLE
Could not resolve name when clicking client API reference on README

### ISSUE THREAD

**Issue by kurthalex** [ipfs/py-ipfs-api#81]
Link to the client API reference is broken in the README page

https://ipfs.io/ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfsapi/

**Comment by alexander255** [comment]
Thanks for the report. I had deleted the entire IPFS configuration on my computer and the node keeping the documentation data around had a bug that caused it to happily remove the data from its own storage as well. It's fixed now! Thanks for the report! 🙂
