### ISSUE TITLE
add only_hash=True

### ISSUE THREAD

**Issue by cappelaere** [ipfs/py-ipfs-api#84]
I am trying to get the hash of an existing file without adding to the IPFS.
ipfs add myfile --only_hash  seems to work
but ipfs_api.add(myfile, only_hash=True):
TypeError: request() got an unexpected keyword argument 'only_hash'

Am I doing something wrong?
Thanks.
Pat.

**Comment by mguentner** [comment]
Without actually testing it: ` ipfs_api.add(yourfile, opts={'only_hash':'true'}` should do the trick

**Comment by whereswaldon** [comment]
@cappelaere While @mguentner 's answer looks right, it's not working for me. I'm trying to debug this now.

**Comment by whereswaldon** [comment]
@cappelaere Alright, I think I've got it:
```python
import ipfsapi
api = ipfsapi.connect('127.0.0.1', 5001)
hash_data = api.add("myfile.txt", opts={'only-hash':'true'})
```
The key is that 'only-hash' uses a hyphen, '-', rather than an underscore, '_'.
Let me know if that solves your problem!
